 /**
  * vuex 封装常量
  * @author zhangtianci
  */
const UPDATA_CONSULTVALUE = "UPDATA_CONSULTVALUE"
const UPDATA_CONSULTDATAS = "UPDATA_CONSULTDATAS"
const UPDATA_CONSULTPAGANO = "UPDATA_CONSULTPAGANO"
const UPDATA_CONSULTCHANNEL = "UPDATA_CONSULTCHANNEL"
const UPDATA_CONSULTSTATUS = "UPDATA_CONSULTSTATUS"
const UPDATA_CONSULTOPERATOR = "UPDATA_CONSULTOPERATOR"
const UPDATA_CONSULTCTIME = "UPDATA_CONSULTCTIME"
const UPDATA_CONSULTUTIME = "UPDATA_CONSULTUTIME"

const UPDATA_MATERIALVALUE = "UPDATA_MATERIALVALUE"
const UPDATA_MATERIAVALUE = "UPDATA_MATERIAVALUE"
const UPDATE_MATERIADATAS = "UPDATE_MATERIADATAS"
const UPDATA_MATERIAPAGANO = "UPDATA_MATERIAPAGANO"
const UPDATA_MATERIADATAS = "UPDATA_MATERIADATAS"
const UPDATA_MATERIAOPERATOR = "UPDATA_MATERIAOPERATOR"
const UPDATA_MATERIASOURCE = "UPDATA_MATERIASOURCE"
const UPDATA_MATERIAUPDATE = "UPDATA_MATERIAUPDATE"
const UPDATA_MATERIACTIME = "UPDATA_MATERIACTIME"
const UPDATA_MATERIAUTIME = "UPDATA_MATERIAUTIME"

const UPDATA_ACTIVITYVALUE = "UPDATA_ACTIVITYVALUE"
const UPDATE_ACTIVITYSTATUS = "UPDATE_ACTIVITYSTATUS"
const UPDATA_ACTIVITYPERATOR = "UPDATA_ACTIVITYPERATOR"
const UPDATA_ACTIVITYCTIME = "UPDATA_ACTIVITYCTIME"
const UPDATA_ACTIVITYUTIME = "UPDATA_ACTIVITYUTIME"


export default {
	UPDATA_CONSULTVALUE,
	UPDATA_CONSULTDATAS,
	UPDATA_CONSULTPAGANO,
	UPDATA_CONSULTCHANNEL,
	UPDATA_CONSULTSTATUS,
	UPDATA_CONSULTOPERATOR,
	UPDATA_CONSULTCTIME,
	UPDATA_CONSULTUTIME,

	UPDATA_MATERIALVALUE,
	UPDATA_MATERIAVALUE,
	UPDATE_MATERIADATAS,
	UPDATA_MATERIAPAGANO,
	UPDATA_MATERIADATAS,
	UPDATA_MATERIAOPERATOR,
	UPDATA_MATERIASOURCE,
	UPDATA_MATERIAUPDATE,
	UPDATA_MATERIACTIME,
	UPDATA_MATERIAUTIME,

	UPDATA_ACTIVITYVALUE,
	UPDATE_ACTIVITYSTATUS,
	UPDATA_ACTIVITYPERATOR,
	UPDATA_ACTIVITYCTIME,
	UPDATA_ACTIVITYUTIME
}
